### ISSUE TITLE
Deletion of some text about how to cite.

### ISSUE THREAD

**Issue by turingfan** [force11/force11-scwg#84] opened 2016-03-30 12:52 UTC
I just opened and closed an issue because I may have misunderstood the text.  So I am reopening this one but would still wish this text to be deleted:

"In addition, if the software authors ask that a paper should be cited, that should be respected."

It's not clear to me if the point being made is what paper to cite once a decision is made to cite some software. 

In fact I feel that sentence is still superfluous and in fact could be deleted, but I feel much less strongly about this. The preceding and succeeding sentences surely cover every case?  I.e. they clearly explain that if i should cite it I should cite it, so I'm not sure what the "in addition" point is.  

On the other hand this sentence could be read as implying that if I use software and the authors want me to cite it, then I should cite it.  This is the point I was addressing earlier, to which I strongly objected.  And which I would stand by if it was interpreted that way.  In that case I would much more strongly urge deletion of that sentence, as per my now closed issue.

**Comment by olexandr-konovalov** [comment] 2016-03-30 13:45
@turingfan I agree that this phrase is ambiguous. My understanding of it when I read it for the first time was "In addition, if the software authors ask that **instead of a software one should cite a particular paper**, that should be respected." In case this coincides with the original idea, I suggest this clarification to avoid misunderstanding.

Also, I suggest to add that in this case one still have to make it clear which **version** of the software is used (either by citing both paper and software, or mentioning the version in the text), since plain reference to a paper does not help with the reproducibility (also, the paper may be N years old so this will not give any credit to developers who may have joined the project later)

**Comment by iherman** [comment] 2016-03-30 13:59
My understanding of the text was the same as @alex-konovalov 's.

**Comment by danielskatz** [comment] 2016-03-30 17:27
The intent of this was to say
1 - you should cite the software release (which inherently is a specific version)
2 - if the authors ask that a software paper also cited, you should

If this doesn't seem to match the text, please suggest specific changes that will address this concern.

**Comment by migueldvb** [comment] 2016-03-30 18:02
I agree with @turingfan's argument on this issue and am +1 on removing this sentence now.
There are some existing software licenses that require that any published results using a piece of software cite a particular paper such as the NAMD license (which is not free software). I have no idea if this kind of clause in license agreements have any legal enforceability but the users should cite the paper if they use the software on published results.
http://www.ks.uiuc.edu/Research/namd/license.html
Maybe it is not worth to mention this kind of licenses in the whitepaper. In the case of most common software licenses one should follow standard rules to cite software products as explained in the previous sentences. I think that it should be the responsability of the authors of the paper to cite their sources, and during peer review the referees of the paper should also make sure that the software that is used is properly cited.

**Comment by kyleniemeyer** [comment] 2016-03-30 18:30
Since we are certainly recommending that software should be cited (including version, and all the other details we have discussed in the document) regardless of anything else, perhaps the statement can be changed to something like "In addition, if the software authors ask that a paper should be cited, that should be respected **and the paper cited in addition to the software**."

I'm sure we all agree that there should be no need to cite the paper on top of the software, but many people/communities will continue to value paper citations over software citations. I see this as a low-cost way to get people to make their software citable, even if they prefer publication of papers—they don't have anything to lose. (If they see making their software citable as "losing out" on citations to their papers, they may be less likely to do so.)

I suppose the counter-argument is that users of software should be citing it regardless of whether the authors "made" it citable, but it isn't hard for me to imagine people not releasing their software openly if they think it will reduce citations of their papers in favor of something that is valued less (in their or others' minds).

We should be principled, but also probably pragmatic. (... some unintentional alliteration there)

**Comment by iliant** [comment] 2016-03-30 18:59
Quite a few good points here.  In terms of promoting the RSE (http://www.rse.ac.uk/) career path in academia the citations of papers "recommended" by software packages will attribute to the citation record of the individuals who (co-)authored the papers outlining specific methodology/functionality used during the run.  This is a common practice for many EU based software projects.  The most valued credibility record recognised by the academic recruitment panels for nearly all research jobs in EU academia (some of which disguise RSE jobs) is the publication record and of course h-index that depends on citations (ditto).  Opening and let alone fitting the RSE career path within the academic ecosystem in the EU is not a trivial task and from my experience and observation the implementation of this task vary greatly between different UK establishments.  So every little bit helps.

Ilian

**Comment by turingfan** [comment] 2016-03-30 20:40
I'm sorry I took the text out of context on the other thread (though I did self-close that immediately). 

In case others are as bad at reading as me, I would suggest changing the earlier sentence

Given a software paper and software, the question of which should be cited and when is complicated, and there is no simple answer.

to be

Where software should be cited, the question of whether to cite the software itself or a software paper is complicated, and there is no simple answer.

For the sentence I suggested deleting, I still would be happy to delete it but I also support Kyle's clarification. I would however suggest adding a word such as normally or typically, e.g. 

In addition, if the software authors ask that a paper should be cited, that should normally be respected and the paper cited in addition to the software.

**Comment by olexandr-konovalov** [comment] 2016-03-30 21:25
I think our audience consists not only from the software users, but also from software developers, and the reader who is a developer may be interested in finding our advice regarding the suggested citation format that _they_ could recommend to their users. 

So while we are combining pragmatism and principality, as @kyleniemeyer says, I would like to suggest to have a note that (while being understandable) the practice of suggesting to cite a paper **instead** of a software has certain disadvantages (no version information; credit only to paper authors). This practice emerged due to the existing system which we are trying to change, and I think we could be clear that we do not consider it as satisfactory.

**Comment by migueldvb** [comment] 2016-03-30 21:52
I feel that it is not great practice to request citation to a paper and we should not endorse or explicitely reject it, but I am fine with keeping this sentence given the good points that have been raised here.

**Comment by kyleniemeyer** [comment] 2016-03-31 00:12
OK—here are the changes that I just made in 52363b6bb538cc8e8b64e9f276e71692e1606ec7
1. Line 390: `In addition, if the software authors ask that a paper should be cited, that should typically be respected and the paper cited in addition to the software. However, the software itself should still be cited.`
2. Lines 384-385: `Where software should be cited, the question of whether to cite the software itself or a software paper is complicated, and there is no simple answer.`

If someone would like to modify or expand upon those, please submit a pull request. Otherwise, I'll close this issue in a day or so.

**Closed as completed** 2016-04-05 17:39 UTC
Labels: addressed - will close soon
